import type { ItemSummary } from '@/components/common/types'

/**
 * Deterministic, offline placeholder thumbnails (inline SVG data URIs) so
 * this page renders identically with no network access — real thumbnails
 * come from arbitrary external hosts once P10/P7 wire the real data, but a
 * dev gallery shouldn't depend on the internet being reachable to prove the
 * components work.
 */
function placeholderThumb(seed: number): string {
  const hue = (seed * 47) % 360
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="320" height="180"><rect width="320" height="180" fill="hsl(${hue} 40% 55%)"/><circle cx="${70 + seed * 12}" cy="100" r="80" fill="hsl(${(hue + 45) % 360} 55% 68%)" opacity=".55"/></svg>`
  return `data:image/svg+xml,${encodeURIComponent(svg)}`
}

const DAY = 86_400_000
const now = Date.now()

/**
 * One item per ItemKind (the enum has 7 values, not 6 — see the final
 * report) plus a spread of statuses/tiers/edge-cases: a metadata_only repo
 * with no summary yet, a still-processing item (shimmering placeholder
 * text), a failed pipeline run, a dropped-not-failed distinction, a long
 * title, and an un-topiced item.
 */
export const FIXTURE_ITEMS: ItemSummary[] = [
  {
    id: 'itm_01',
    kind: 'github',
    status: 'inbox',
    title: 'agentic-rag-evals',
    author: 'letta-ai',
    url: 'https://github.com/letta-ai/agentic-rag-evals',
    canonical_url: 'https://github.com/letta-ai/agentic-rag-evals',
    thumbnail_url: null,
    extraction_tier: 'full',
    source_surface: 'extension',
    summary_tldr:
      'A harness for scoring agentic RAG pipelines on retrieval faithfulness and answer relevancy separately, with a 200-query golden set.',
    topic: { slug: 'rag-evals', label: 'RAG Evals', color: '#6366f1', confidence: 0.91 },
    tags: ['rag', 'evals', 'agents'],
    starred: true,
    board_rank: 1,
    created_at: now - 1 * DAY,
    updated_at: now - 1 * DAY,
    last_opened_at: now - 1 * DAY,
  },
  {
    id: 'itm_02',
    kind: 'video',
    status: 'testing',
    title: 'Video diffusion fine-tuning, end to end',
    author: 'ml-explained',
    url: 'https://www.youtube.com/watch?v=abc123',
    canonical_url: 'https://www.youtube.com/watch?v=abc123',
    thumbnail_url: placeholderThumb(2),
    extraction_tier: 'partial',
    source_surface: 'extension',
    summary_tldr:
      'Walks through LoRA fine-tuning a video diffusion checkpoint on a custom motion dataset, with a comparison against full fine-tuning.',
    topic: { slug: 'diffusion-models', label: 'Diffusion Models', color: '#0ea5e9', confidence: 0.86 },
    tags: ['diffusion', 'fine-tuning'],
    starred: false,
    board_rank: 2,
    created_at: now - 2 * DAY,
    updated_at: now - 2 * DAY,
    last_opened_at: null,
  },
  {
    id: 'itm_03',
    kind: 'article',
    status: 'tested',
    title: 'Why hybrid search beats pure vector search in production',
    author: 'Anh Le',
    url: 'https://example.com/hybrid-search',
    canonical_url: 'https://example.com/hybrid-search',
    thumbnail_url: null,
    extraction_tier: 'full',
    source_surface: 'web',
    summary_tldr:
      'Argues BM25 + dense retrieval fused with RRF consistently beats either alone once queries include exact identifiers, and shows the eval numbers.',
    topic: { slug: 'search', label: 'Search', color: '#22c55e', confidence: 0.95 },
    tags: ['search', 'rrf', 'bm25'],
    starred: false,
    board_rank: 3,
    created_at: now - 5 * DAY,
    updated_at: now - 3 * DAY,
    last_opened_at: now - 3 * DAY,
  },
  {
    id: 'itm_04',
    kind: 'social',
    status: 'to_test',
    title: null,
    author: '@simonw',
    url: 'https://x.com/simonw/status/999',
    canonical_url: 'https://x.com/simonw/status/999',
    thumbnail_url: null,
    extraction_tier: 'full',
    source_surface: 'extension',
    summary_tldr: 'An 8-post thread arguing structured tool-calling beats prompt-and-repair for schema reliability, with benchmarks across six models.',
    topic: { slug: 'llm-tooling', label: 'LLM Tooling', color: '#f97316', confidence: 0.78 },
    tags: ['structured-output'],
    starred: false,
    board_rank: 4,
    created_at: now - 6 * DAY,
    updated_at: now - 6 * DAY,
    last_opened_at: null,
  },
  {
    id: 'itm_05',
    kind: 'pdf',
    status: 'inbox',
    title: 'Contextual Retrieval for Long-Document RAG (arXiv:2506.01234)',
    author: 'Chen et al.',
    url: 'https://arxiv.org/abs/2506.01234',
    canonical_url: 'https://arxiv.org/abs/2506.01234',
    thumbnail_url: null,
    extraction_tier: 'metadata_only',
    source_surface: 'web',
    summary_tldr: null,
    topic: null,
    tags: [],
    starred: false,
    board_rank: 5,
    created_at: now - 0.2 * DAY,
    updated_at: now - 0.2 * DAY,
    last_opened_at: null,
  },
  {
    id: 'itm_06',
    kind: 'audio',
    status: 'archived',
    title: 'Latent Space Podcast — The state of open-weight reasoning models',
    author: 'Latent Space',
    url: 'https://example.com/podcast/42',
    canonical_url: 'https://example.com/podcast/42',
    thumbnail_url: null,
    extraction_tier: 'full',
    source_surface: 'web',
    summary_tldr: 'Covers the current crop of open-weight reasoning models, their eval gaps versus closed frontier models, and inference cost tradeoffs.',
    topic: { slug: 'open-models', label: 'Open Models', color: '#a855f7', confidence: 0.82 },
    tags: ['podcast', 'reasoning'],
    starred: false,
    board_rank: 6,
    created_at: now - 20 * DAY,
    updated_at: now - 18 * DAY,
    last_opened_at: now - 18 * DAY,
  },
  {
    id: 'itm_07',
    kind: 'other',
    status: 'dropped',
    title: 'A Google Sheet someone shared with "benchmarks" in it',
    author: null,
    url: 'https://docs.example.com/sheet/xyz',
    canonical_url: 'https://docs.example.com/sheet/xyz',
    thumbnail_url: null,
    extraction_tier: 'partial',
    source_surface: 'import',
    summary_tldr: 'Numbers didn’t cite a source and couldn’t be reproduced — not worth citing.',
    topic: null,
    tags: [],
    starred: false,
    board_rank: 7,
    created_at: now - 30 * DAY,
    updated_at: now - 10 * DAY,
    last_opened_at: now - 10 * DAY,
  },
  {
    id: 'itm_08',
    kind: 'github',
    status: 'failed',
    title:
      'an-extremely-long-repository-name-that-explains-exactly-what-it-does-in-the-slug-itself-instead-of-the-readme',
    author: 'someone',
    url: 'https://github.com/someone/an-extremely-long-repository-name',
    canonical_url: 'https://github.com/someone/an-extremely-long-repository-name',
    thumbnail_url: null,
    extraction_tier: 'metadata_only',
    source_surface: 'extension',
    summary_tldr: null,
    topic: null,
    tags: [],
    starred: false,
    board_rank: 8,
    created_at: now - 0.05 * DAY,
    updated_at: now - 0.01 * DAY,
    last_opened_at: null,
  },
  {
    id: 'itm_09',
    kind: 'video',
    status: 'queued',
    title: 'Reel: "this changes everything 🤯"',
    author: '@ai.daily',
    url: 'https://www.instagram.com/reel/xyz',
    canonical_url: 'https://www.instagram.com/reel/xyz',
    thumbnail_url: placeholderThumb(9),
    extraction_tier: 'metadata_only',
    source_surface: 'pwa',
    summary_tldr: null,
    topic: null,
    tags: [],
    starred: false,
    board_rank: 9,
    created_at: now - 60_000,
    updated_at: now - 60_000,
    last_opened_at: null,
  },
  {
    id: 'itm_10',
    kind: 'article',
    status: 'processing',
    title: 'Batching relation-labeling sweeps to stay inside a free-tier budget',
    author: 'eng blog',
    url: 'https://example.com/batching-llm-calls',
    canonical_url: 'https://example.com/batching-llm-calls',
    thumbnail_url: null,
    extraction_tier: 'full',
    source_surface: 'web',
    summary_tldr: null,
    topic: null,
    tags: [],
    starred: false,
    board_rank: 10,
    created_at: now - 30_000,
    updated_at: now - 5_000,
    last_opened_at: null,
  },
]
